# Generated by Django 4.2.5 on 2024-01-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naming", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UniversitiesFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_naming", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("teacher", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                (
                    "universities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities_faculty",
                        to="educational.universities",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniversitiesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="universities_image/")),
                (
                    "universities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="educational.universities",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniversitiesFacultyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="universities_faculty_image/")),
                (
                    "universities_faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="educational.universitiesfaculty",
                    ),
                ),
            ],
        ),
    ]
