# Generated by Django 4.2.5 on 2024-01-29 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("gpa", models.FloatField()),
                ("sat_act", models.FloatField()),
                ("ielts", models.FloatField(blank=True)),
                ("toefl", models.FloatField(blank=True)),
                (
                    "essay",
                    models.FileField(
                        blank=True, upload_to="case_essay/", verbose_name="case_essay"
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=60)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=60)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="educ_history/",
                        verbose_name="Education_History",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educ_history",
                        to="case.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educ_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="achievements_case/",
                        verbose_name="Achievements_Case",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=60)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements_case",
                        to="case.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements_case",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
