# Generated by Django 4.2.5 on 2024-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="essay",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="case_essay/",
                verbose_name="case_essay",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="ielts",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="toefl",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
