# Generated by Django 4.2.5 on 2024-01-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case", "0002_alter_case_essay_alter_case_ielts_alter_case_toefl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
